//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Pages
{


    public partial class Dashboard
    {

        /// <summary>
        /// UserNavbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PharmacyManagementSystem.Controls.Navbar UserNavbar;

        /// <summary>
        /// UserFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PharmacyManagementSystem.Controls.Footer UserFooter;
    }
}
